package snowman;

import snowman.command.Command;
import snowman.command.Parser;
import snowman.storage.Storage;
import snowman.task.TaskList;
import snowman.ui.Ui;

/**
 * Represents the Snowman chatbot application.
 * The Snowman class initializes the user interface, storage, and task list,
 * and handles execution of user commands. It supports both console and GUI modes.
 */
public class Snowman {
    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;

    private String commandType;

    /**
     * Constructs a Snowman application instance.
     * <p>
     * Initializes the user interface, storage, and task list using the provided file path.
     *
     * @param filePath Path to the file used for saving and loading tasks.
     */
    public Snowman(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        tasks = new TaskList(storage.load());
    }

    /**
     * Runs the Snowman application in console mode.
     * Displays a welcome message, then repeatedly reads user commands,
     * parses and executes them, handles errors, and terminates when an ExitCommand is issued.
     */
    public void run() {
        ui.showWelcome();
        boolean isExit = false;
        while (!isExit) {
            try {
                String fullCommand = ui.readCommand();
                ui.showLine(); // show the divider line ("_______")
                Command c = Parser.parse(fullCommand);
                c.execute(tasks, ui, storage);
                isExit = c.isExit();
            } catch (SnowmanException e) {
                ui.showError(e.getMessage());
            } finally {
                ui.showLine();
            }
        }
    }

    /**
     * Starts the Snowman application with a default storage file.
     *
     * @param args Command-line arguments (ignored).
     */
    public static void main(String[] args) {
        new Snowman("data/storage.txt").run();
    }

    /**
     * Generates a response string for a given user input in GUI mode.
     * Parses the input into a command, executes it, and returns the resulting feedback.
     *
     * @param input User input string.
     * @return Feedback string generated by executing the corresponding command.
     */
    public String getResponse(String input) {
        try {
            Command c = Parser.parse(input);
            c.execute(tasks, ui, storage);
            commandType = c.getClass().getSimpleName();
            return c.getString();
        } catch (SnowmanException e) {
            return "Error: " + e.getMessage();
        }
    }

    /**
     * Returns the type of the most recently executed command.
     *
     * @return Command class name of the last executed command.
     */
    public String getCommandType() {
        return commandType;
    }
}
